--Ho va ten:		La Quoc Thang
--Ngay thuc hien:	8/10/2019

USE MASTER
GO

SET DATEFORMAT dmy;

CREATE DATABASE QLNV ON 
(
	NAME = QLNV,
	FILENAME = 'D:\OneDrive\Thang\HOCTAP\2019-2020\HKI\HQTCSDL\Lab\QLNV.MDF',
	SIZE = 10 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 5 MB
) 
LOG ON 
(
	NAME = QLNV_LOG,
	FILENAME = 'D:\OneDrive\Thang\HOCTAP\2019-2020\HKI\HQTCSDL\Lab\QLNV_LOG.LDF',
	SIZE = 5 MB,
	MAXSIZE = 25 MB,
	FILEGROWTH = 5 MB
)
GO

USE QLNV
GO

CREATE TABLE PHONG
(
	MAPHONG CHAR(3),
	TENPHONG NVARCHAR(40),
	DIACHI NVARCHAR(50),
	TEL CHAR(10),
	CONSTRAINT [PK_MAPHONG] PRIMARY KEY (MAPHONG)
)
GO

CREATE TABLE DMNN
(
	MANN CHAR(2),
	TENNN NVARCHAR(20),
	CONSTRAINT [PK_MANN] PRIMARY KEY (MANN)
)
GO

CREATE TABLE NHANVIEN
(
	MANV CHAR(5),
	HOTEN NVARCHAR(40),
	GIOITINH NCHAR(3),
	NGAYSINH DATETIME,
	LUONG INT,
	MAPHONG CHAR(3),
	SDT CHAR(10),
	NGAYBC DATETIME,
	CONSTRAINT [PK_MANV] PRIMARY KEY (MANV),
	FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
)
GO

CREATE TABLE TDNN
(
	MANV CHAR(5),
	MANN CHAR(2),
	TDO CHAR,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MANN) REFERENCES DMNN(MANN),
	CONSTRAINT [PK_TDNN] PRIMARY KEY (MANV, MANN)
)
GO

CREATE PROCEDURE USP_ADD_PHONG
	@MAPHONG CHAR(3),
	@TENPHONG NVARCHAR(40),
	@DIACHI NVARCHAR(50),
	@TEL CHAR(10)
AS
IF NOT EXISTS (SELECT *
FROM PHONG
WHERE MAPHONG = @MAPHONG)
	INSERT INTO PHONG
VALUES
	(@MAPHONG, @TENPHONG, @DIACHI, @TEL)
GO

EXEC USP_ADD_PHONG 'HCA', N'HÀNH CHÍNH TỔ HỢP', N'123, LÁNG HẠ, ĐỐNG ĐA, HÀ NỘI', '048585793'
EXEC USP_ADD_PHONG 'KDA', N'KINH DOANH', N'123, LÁNG HẠ, ĐỐNG ĐA, HÀ NỘI', '048574943'
EXEC USP_ADD_PHONG 'KTA', N'KY THUAT', N'123, LÁNG HẠ, ĐỐNG ĐA, HÀ NỘI', '049480485'
EXEC USP_ADD_PHONG 'QTA', N'QUAN TRI', N'123, LÁNG HẠ, ĐỐNG ĐA, HÀ NỘI', '048508585'
GO

CREATE PROCEDURE USP_ADD_DMNN
	@MANN CHAR(2),
	@TENNN NVARCHAR(20)
AS
IF NOT EXISTS (SELECT *
FROM DMNN
WHERE MANN = @MANN)
	INSERT INTO DMNN
VALUES
	(@MANN, @TENNN)
GO

EXEC USP_ADD_DMNN '01', N'ANH'
EXEC USP_ADD_DMNN '02', N'NGA'
EXEC USP_ADD_DMNN '03', N'PHÁP'
EXEC USP_ADD_DMNN '04', N'NHẬT'
EXEC USP_ADD_DMNN '05', N'TRUNG QUỐC'
EXEC USP_ADD_DMNN '06', N'HÀN QUỐC'
GO

CREATE PROCEDURE USP_ADD_NHANVIEN
	@MANV CHAR(5),
	@HOTEN NVARCHAR(40),
	@GIOITINH CHAR(3),
	@NGAYSINH DATETIME,
	@LUONG INT,
	@MAPHONG CHAR(3),
	@SDT CHAR(10),
	@NGAYBC DATETIME
AS
IF NOT EXISTS (SELECT *
FROM NHANVIEN
WHERE MANV = @MANV)
	INSERT INTO NHANVIEN
VALUES
	(@MANV, @HOTEN, @GIOITINH, @NGAYSINH, @LUONG, @MAPHONG, @SDT, @NGAYBC)
GO

EXEC USP_ADD_NHANVIEN 'HC001', N'Nguyễn Thị Hà', N'Nữ', '27/8/1950', '2500000', 'HCA', '', '8/2/1975'
EXEC USP_ADD_NHANVIEN 'HC002', N'Trần Văn Nam', N'Nam', '12/6/1975', '3000000', 'HCA', '', '8/6/1997'
EXEC USP_ADD_NHANVIEN 'HC003', N'Nguyễn Thanh Huyền', N'Nữ', '3/7/1978', '1500000', 'HCA', '', '24/9/1999'
EXEC USP_ADD_NHANVIEN 'KD001', N'Lê Tuyết Anh', N'Nữ', '3/2/1977', '2500000', 'KDA', '', '2/10/2001'
EXEC USP_ADD_NHANVIEN 'KD002', N'Nguyễn Anh Tú', N'Nam', '4/7/1942', '2600000', 'KDA', '', '24/9/1999'
EXEC USP_ADD_NHANVIEN 'KD003', N'Phạm An Thái', N'Nam', '9/5/1977', '1600000', 'KDA', '', '24/9/1999'
EXEC USP_ADD_NHANVIEN 'KD004', N'Lê Văn Hải', N'Nam', '2/1/1976', '2700000', 'KDA', '', '8/6/1997'
EXEC USP_ADD_NHANVIEN 'KD005', N'Nguyễn Phương Minh', N'Nam', '2/1/1980', '2000000', 'KDA', '', '2/10/2001'
EXEC USP_ADD_NHANVIEN 'KT001', N'Trần Đình Khâm', N'Nam', '2/12/1981', '2700000', 'KTA', '', '1/1/2005'
EXEC USP_ADD_NHANVIEN 'KT002', N'Nguyễn Mạnh Hùng', N'Nam', '16/8/1980', '2300000', 'KTA', '', '1/1/2005'
EXEC USP_ADD_NHANVIEN 'KT003', N'Phạm Thanh Sơn', N'Nam', '20/8/1984', '2000000', 'KTA', '', '1/1/2005'
EXEC USP_ADD_NHANVIEN 'KT004', N'Vũ Thị Hoài', N'Nữ', '5/12/1980', '2500000', 'KTA', '', '2/10/2001'
EXEC USP_ADD_NHANVIEN 'KT005', N'Nguyễn Thu Lan', N'Nữ', '5/10/1977', '3000000', 'KTA', '', '2/10/2001'
EXEC USP_ADD_NHANVIEN 'KT006', N'Trần Hoài Nam', N'Nam', '2/7/1978', '2800000', 'KTA', '', '8/6/1997'
EXEC USP_ADD_NHANVIEN 'KT007', N'Hoàng Nam Sơn', N'Nam', '3/12/1940', '3000000', 'KTA', '', '2/7/1965'
EXEC USP_ADD_NHANVIEN 'KT008', N'Lê Thu Trang', N'Nữ', '6/7/1950', '2500000', 'KTA', '', '2/8/1968'
EXEC USP_ADD_NHANVIEN 'KT009', N'Khúc Nam Hải', N'Nam', '22/7/1980', '2000000', 'KTA', '', '1/1/2005'
EXEC USP_ADD_NHANVIEN 'KT010', N'Phùng Trung Dũng', N'Nam', '28/8/1978', '2200000', 'KTA', '', '24/9/1999'
GO

CREATE PROCEDURE USP_ADD_TDNN
	@MANV CHAR(5),
	@MANN CHAR(2),
	@TDO CHAR
AS
IF NOT EXISTS (SELECT *
FROM TDNN
WHERE MANV = @MANV AND MANN = @MANN)
	INSERT INTO TDNN
VALUES
	(@MANV, @MANN, @TDO)
GO

EXEC USP_ADD_TDNN 'HC001', '01', 'A'
EXEC USP_ADD_TDNN 'HC001', '02', 'B' 
EXEC USP_ADD_TDNN 'HC002', '01', 'C'
EXEC USP_ADD_TDNN 'HC002', '03', 'C'
EXEC USP_ADD_TDNN 'HC003', '01', 'D'
EXEC USP_ADD_TDNN 'KD001', '01', 'C'
EXEC USP_ADD_TDNN 'KD001', '02', 'B'
EXEC USP_ADD_TDNN 'KD002', '01', 'D'
EXEC USP_ADD_TDNN 'KD002', '02', 'A'
EXEC USP_ADD_TDNN 'KD003', '01', 'B'
EXEC USP_ADD_TDNN 'KD003', '02', 'C'
EXEC USP_ADD_TDNN 'KD004', '01', 'C'
EXEC USP_ADD_TDNN 'KD004', '04', 'A'
EXEC USP_ADD_TDNN 'KD004', '05', 'A'
EXEC USP_ADD_TDNN 'KD005', '01', 'B'
EXEC USP_ADD_TDNN 'KD005', '02', 'D'
EXEC USP_ADD_TDNN 'KD005', '03', 'B'
EXEC USP_ADD_TDNN 'KD005', '04', 'B'
EXEC USP_ADD_TDNN 'KT001', '01', 'D'
EXEC USP_ADD_TDNN 'KT001', '04', 'E'
EXEC USP_ADD_TDNN 'KT002', '01', 'C'
EXEC USP_ADD_TDNN 'KT002', '02', 'B'
EXEC USP_ADD_TDNN 'KT003', '01', 'D'
EXEC USP_ADD_TDNN 'KT003', '03', 'C'
EXEC USP_ADD_TDNN 'KT004', '01', 'D'
EXEC USP_ADD_TDNN 'KT005', '01', 'C'
GO

--Bài 3:
SET DATEFORMAT DMY
EXEC USP_ADD_NHANVIEN 'QT001', N'La Quốc Thắng', 'Nam', '5/7/1998', '150000', 'QTA', '', '10/8/2019'
EXEC USP_ADD_TDNN 'QT001', '01', 'C'
EXEC USP_ADD_TDNN 'QT001', '04', 'A'
GO

SELECT *
FROM NHANVIEN NV, TDNN TD
WHERE NV.MANV = 'QT001' AND TD.MANV = 'QT001'

--Bài 4:
--1.	Đưa ra thông tin của nhân viên có mã số KT001?
SELECT *
FROM NHANVIEN
WHERE MANV = 'KT001'

--2.	Hãy sửa họ tên nhân viên trên thành ký tự tiếng Việt (Unicode)
--3.	Đưa ra danh sách các nhân viên nữ?
SELECT *
FROM NHANVIEN
WHERE GIOITINH = N'Nữ'

--4.	Tìm những nhân viên có họ ‘Nguyễn’?
SELECT *
FROM NHANVIEN
WHERE HOTEN LIKE N'Nguyễn%'

--5.	Đưa ra danh sách các nhân viên có tên chứa từ ‘Văn’
SELECT *
FROM NHANVIEN
WHERE HOTEN LIKE N'%Văn%'

--6.	Đưa ra những nhân viên có tuổi dưới 30? (Đưa ra cả thông tin tuổi trong kết quả)
SELECT MANV, HOTEN, GIOITINH, NGAYSINH, LUONG, MAPHONG, SDT, NGAYBC, DATEDIFF(YEAR, GETDATE(), NGAYSINH) AS 'TUOI'
FROM NHANVIEN
WHERE DATEDIFF(YEAR, NGAYSINH, GETDATE()) < 30

--7.	Đưa ra danh sách các nhân viên có tuổi nằm trong khoảng 25 đến 30 tuổi? (Đưa ra cả thông tin tuổi trong kết quả)
SELECT MANV, HOTEN, GIOITINH, NGAYSINH, LUONG, MAPHONG, SDT, NGAYBC, DATEDIFF(YEAR, GETDATE(), NGAYSINH) AS 'TUOI'
FROM NHANVIEN
WHERE DATEDIFF(YEAR, NGAYSINH, GETDATE()) BETWEEN 25 AND 30

--8.	Đưa ra các mã nhân viên đã học các ngoại ngữ 01 ở trình độ C trở lên?
SELECT *
FROM NHANVIEN NV, TDNN TD
WHERE NV.MANV = TD.MANV AND TD.TDO = 'C' AND TD.MANN = '01'

--9.	Đưa ra danh sách các nhân viên vào biên chế trước năm 2000?
SELECT *
FROM NHANVIEN
WHERE YEAR(NGAYBC) < 2000

--10.	Đưa ra danh sách các nhân viên đã vào biên chế hơn 10 năm?
SELECT *
FROM NHANVIEN
WHERE DATEDIFF(YEAR, NGAYBC, GETDATE()) > 10

--11.	Đưa ra danh sách các nhân viên năm nay đủ tuổi nghỉ hưu (Nam >=60 tuổi, Nữ >=55 tuổi)?
SELECT *
FROM NHANVIEN
WHERE GIOITINH = 'Nam' AND DATEDIFF(YEAR, NGAYSINH, GETDATE()) >= 60 OR
	GIOITINH = N'Nữ' AND DATEDIFF(YEAR, NGAYSINH, GETDATE()) >= 55

--12.	Cho biết thông tin (Mã phòng, tên phòng, điện thoại liên hệ) về các phòng ban?
SELECT MAPHONG, TENPHONG, TEL
FROM PHONG

--13.	Đưa ra thông tin (họ tên, ngày sinh, ngày vào biên chế) về 2 nhân viên đầu tiên trong bảng nhân viên?
SELECT TOP(2) HOTEN, NGAYSINH, NGAYBC
FROM NHANVIEN

--14.	Cho biết mã nhân viên, họ tên, ngày sinh, lương của các nhân viên có lương nằm trong khoảng từ 2.000.000 đồng đến 3.000.000 đồng?
SELECT MANV, HOTEN, NGAYSINH, LUONG
FROM NHANVIEN
WHERE LUONG BETWEEN 2000000 AND 3000000

--15.	Đưa ra danh sách các nhân viên chưa có số điện thoại?
SELECT *
FROM NHANVIEN
WHERE SDT = ''

--16.	Đưa ra danh sách các nhân viên sinh nhật trong tháng 3
SELECT *
FROM NHANVIEN
WHERE MONTH(NGAYSINH) = 3

--17.	Hãy đưa ra danh sách nhân viên theo theo chiều tăng dần của lương?
SELECT *
FROM NHANVIEN
ORDER BY LUONG ASC

--18.	Cho biết lương trung bình của phòng Kinh doanh?
SELECT AVG(LUONG) AS N'Lương trung bình', P.MAPHONG, P.TENPHONG
FROM NHANVIEN NV, PHONG P
WHERE NV.MAPHONG = P.MAPHONG AND P.TENPHONG = N'KINH DOANH'
GROUP BY P.MAPHONG, P.TENPHONG

--19.	Cho biết tổng số nhân viên và trung bình lương phòng Kinh doanh?
SELECT COUNT(*) AS N'Tổng số nhân viên', AVG(LUONG) as N'Lương trung bình'
FROM NHANVIEN NV, PHONG P
WHERE NV.MAPHONG = P.MAPHONG AND P.TENPHONG = N'KINH DOANH'

--20.	Cho biết tổng lương của mỗi phòng?
SELECT P.MAPHONG, P.TENPHONG, SUM(LUONG) AS N'Tổng lương'
FROM NHANVIEN NV, PHONG P
WHERE NV.MAPHONG = P.MAPHONG
GROUP BY P.MAPHONG, P.TENPHONG

--21.	Cho biết các phòng có tổng lương lớn hơn 500.0000?
SELECT P.MAPHONG, P.TENPHONG, SUM(LUONG) AS N'Tổng lương'
FROM NHANVIEN NV, PHONG P
WHERE NV.MAPHONG = P.MAPHONG
GROUP BY P.MAPHONG, P.TENPHONG
HAVING SUM(LUONG) > 500000

--22.	Cho biết danh sách mã nhân viên, họ tên, mã phòng và tên phòng họ làm việc?
SELECT MANV, HOTEN, NV.MAPHONG, TENPHONG
FROM NHANVIEN NV, PHONG P
WHERE NV.MAPHONG = P.MAPHONG

--23.	Đưa ra danh sách tất cả các nhân viên cùng với thông tin về phòng ban của họ (kể cả các nhân viên chưa ở phòng nào)?
SELECT *
FROM NHANVIEN NV
LEFT JOIN PHONG P
ON NV.MAPHONG = P.MAPHONG

--24.	Đưa ra danh sách tất cả các phòng cùng với thông tin về các nhân viên của các phòng (kể cả các phòng chưa có nhân viên nào)?
SELECT *
FROM NHANVIEN NV
RIGHT JOIN PHONG P
ON NV.MAPHONG = P.MAPHONG
