USE QLNV
GO

--VIEW NV_TRE

CREATE VIEW [dbo].[VIEW_NV_TRE]
	AS SELECT *, DATEDIFF(YEAR, NGAYSINH, GETDATE()) AS TUOI FROM NHANVIEN
	WHERE DATEDIFF(YEAR, NGAYSINH, GETDATE()) < 35
GO

SELECT * FROM VIEW_NV_TRE
WHERE TUOI BETWEEN 25 AND 30
GO

--VIEW DSTA

CREATE VIEW [dbo].[VIEW_DSTA]
	AS SELECT NV.MANV, HOTEN, NGAYSINH, GIOITINH, TENPHONG, TDO
	FROM NHANVIEN NV, TDNN TD, PHONG P
	WHERE NV.MANV = TD.MANV AND P.MAPHONG = NV.MAPHONG AND MANN = '01'
GO

SELECT * FROM VIEW_DSTA
WHERE TDO != 'A' AND TDO != 'B'
GO

--VIEW TAKD

CREATE VIEW [dbo].[VIEW_TAKD]
	AS SELECT *
	FROM VIEW_DSTA
	WHERE TENPHONG = 'KINH DOANH'
GO

-- Thủ tục Add_NhanVien_2

SET DATEFORMAT DMY
GO

CREATE PROCEDURE ADD_NHANVIEN_2
	@MANV CHAR(5),
	@HOTEN NVARCHAR(40),
	@GIOITINH CHAR(3),
	@NGAYSINH DATETIME,
	@LUONG INT,
	@MAPHONG CHAR(3),
	@SDT CHAR(10),
	@NGAYBC DATETIME,
	@KETQUA BIT OUTPUT
AS
BEGIN
	IF EXISTS (SELECT * FROM PHONG
	WHERE MAPHONG = @MAPHONG)
		BEGIN
			INSERT INTO NHANVIEN VALUES (@MANV, @HOTEN, @GIOITINH, @NGAYSINH, @LUONG, @MAPHONG, @SDT, @NGAYBC)
		END
	ELSE
		SET @KETQUA = 0
END
GO

DECLARE @KQ BIT
EXEC ADD_NHANVIEN_2 'KT011', N'La Quốc Thắng', N'Nam', '5/7/1998', '8000000', 'KTA', '0987610260', '7/11/2019', @KQ OUTPUT
PRINT N'Kết quả thực hiện: ' + CAST(@KQ AS CHAR)
GO

-- Kiểm tra mã nhân viên và mã phòng

ALTER PROCEDURE ADD_NHANVIEN_2
	@MANV CHAR(5),
	@HOTEN NVARCHAR(40),
	@GIOITINH CHAR(3),
	@NGAYSINH DATETIME,
	@LUONG INT,
	@MAPHONG CHAR(3),
	@SDT CHAR(10),
	@NGAYBC DATETIME,
	@KETQUA BIT OUTPUT
AS
BEGIN
	IF EXISTS (SELECT * FROM NHANVIEN
	WHERE MANV = @MANV)
		SET @KETQUA = 0
	IF NOT EXISTS (SELECT * FROM PHONG
	WHERE MAPHONG = @MAPHONG)
		SET @KETQUA = 1
	IF @KETQUA = 0 OR @KETQUA = 1
		INSERT INTO NHANVIEN VALUES (@MANV, @HOTEN, @GIOITINH, @NGAYSINH, @LUONG, @MAPHONG, @SDT, @NGAYBC)
END
GO

DECLARE @KQ BIT
EXEC ADD_NHANVIEN_2 'KT011', N'La Quốc Thắng', N'Nam', '5/7/1998', '8000000', 'KTA', '', '7/11/2019', @KQ OUTPUT
PRINT N'Kết quả thực hiện: ' + CAST(@KQ AS CHAR)
GO

-- Cập nhật số điện thoại cho các nhân viên

CREATE PROCEDURE ADD_PHONENUMBER
	@MANV CHAR(5),
	@SDT CHAR(10),
	@KQ BIT OUTPUT
AS
BEGIN
	IF EXISTS (SELECT * FROM NHANVIEN
	WHERE MANV = @MANV)
		UPDATE NHANVIEN
		SET SDT = @SDT
		WHERE MANV = @MANV
	ELSE
		SET @KQ = 0
END
GO

--DECLARE @KQ BIT
EXEC ADD_PHONENUMBER 'KT012', '0987610260', @KQ OUTPUT
PRINT N'Kết quả thực hiện: ' + CAST(@KQ AS CHAR)
GO

-- Thủ tục tính tổng số nhân viên có độ tuổi trong khoảng xác định

CREATE PROCEDURE SONHANVIEN_TRONGDOTUOI
	@TUOI1 TINYINT,
	@TUOI2 TINYINT,
	@SOLUONG INT OUTPUT
AS
BEGIN
	SET @SOLUONG = (SELECT COUNT(*)
	FROM NHANVIEN
	WHERE DATEDIFF(YEAR, NGAYSINH, GETDATE()) BETWEEN @TUOI1 AND @TUOI2)
END
GO

DECLARE @KQ INT
EXEC SONHANVIEN_TRONGDOTUOI 20, 30, @KQ OUTPUT
PRINT N'Kết quả thực hiện: ' + CAST(@KQ AS CHAR)
GO

-- Thủ tục tính tổng số nhân viên đã học ngoại ngữ 

CREATE PROCEDURE SONHANVIEN_HOCNGOAINGU
	@TENNN NVARCHAR(20),
	@SOLUONG INT OUTPUT
AS
BEGIN
	SET @SOLUONG = (SELECT COUNT(*)
	FROM TDNN TD, NHANVIEN NV, DMNN DM
	WHERE TD.MANN = DM.MANN AND TD.MANV = NV.MANV AND TENNN = @TENNN)
END
GO

DECLARE @KQ INT
EXEC SONHANVIEN_HOCNGOAINGU 'NGA', @KQ OUTPUT
PRINT N'Kết quả thực hiện: ' + CAST(@KQ AS CHAR)
GO

-- Ràng buộc 1. Tên phòng là duy nhất

ALTER TABLE PHONG
ADD UNIQUE (TENPHONG)
GO

-- Ràng buộc 2. Tên ngoại ngữ là duy nhất

ALTER TABLE DMNN
ADD UNIQUE (TENNN)
GO

-- Ràng buộc 3. Lương trong bảng nhân viên luôn >= 0, giá trị mặc định là 0

ALTER TABLE NHANVIEN
ADD CHECK (LUONG >= 0), DEFAULT 0 FOR LUONG
GO

-- Ràng buộc 4. Thêm và xóa tham chiếu mã phòng trong bảng nhân viên đến mã phòng trong bảng phòng

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_MAPHONG_NHANVIEN
FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
GO

ALTER TABLE NHANVIEN
DROP CONSTRAINT FK_MAPHONG_NHANVIEN;
GO

-- Ràng buộc 5. 

-- Ràng buộc 6. TDO trong TDNN nhận một trong các giá trị từ A đến F và mặc định là A

ALTER TABLE TDNN
ADD CHECK (TDO IN ('A', 'B', 'C', 'D', 'E', 'F')), DEFAULT 'A' FOR TDO