USE MASTER
GO

SET DATEFORMAT dmy;

CREATE DATABASE QLD ON 
(
	NAME = QLD,
	FILENAME = 'D:\OneDrive\Thang\HOCTAP\2019-2020\HKI\HQTCSDL\Lab\QLD.MDF',
	SIZE = 10 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 5 MB
) 
LOG ON 
(
	NAME = QLD_LOG,
	FILENAME = 'D:\OneDrive\Thang\HOCTAP\2019-2020\HKI\HQTCSDL\Lab\QLD_LOG.LDF',
	SIZE = 5 MB,
	MAXSIZE = 25 MB,
	FILEGROWTH = 5 MB
)
GO

USE QLD
GO

CREATE TABLE KHOA
(
	MAKHOA INT,
	TENKHOA NVARCHAR(100),
	DIACHI NVARCHAR(300),
	CONSTRAINT [PK_MAKHOA] PRIMARY KEY (MAKHOA),
	CONSTRAINT U_TENKHOA UNIQUE NONCLUSTERED (TENKHOA)
)
GO

CREATE TABLE SINHVIEN
(
	MASV INT IDENTITY(1,1),
	HO NVARCHAR(100),
	TEN NVARCHAR(100),
	NGAYSINH DATETIME,
	GIOITINH NVARCHAR(3) DEFAULT N'Nữ',
	MAKHOA INT,
	CONSTRAINT [PK_MASV] PRIMARY KEY (MASV),
	CONSTRAINT [FK_SINHVIEN] FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
	CONSTRAINT [CHK_GIOITINH] CHECK (GIOITINH IN (N'Nam', N'Nữ'))
)
GO

CREATE TABLE MONHOC
(
	MAMH INT,
	TENMH NVARCHAR(100) NOT NULL,
	DVHT TINYINT DEFAULT 3,
	HOCKY TINYINT,
	CONSTRAINT [PK_MAMH] PRIMARY KEY (MAMH)
)
GO

CREATE TABLE KETQUA
(
	MASV INT,
	MAMH INT,
	DIEM FLOAT,
	CONSTRAINT [FK_MASV] FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
	CONSTRAINT [FK_MAMH] FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT [PK_KETQUA] PRIMARY KEY (MASV, MAMH),
	CONSTRAINT [CHK_DIEM] CHECK (DIEM BETWEEN 0 AND 10)
)
GO

--Thêm dữ liệu
INSERT INTO KHOA VALUES (1, 'Công nghệ thông tin', 'Thư viện cũ')
INSERT INTO KHOA VALUES (2, 'Quản trị kinh doanh', 'A7')
INSERT INTO KHOA VALUES (3, 'Sinh học', 'A8')
INSERT INTO KHOA VALUES (4, 'Ngoại ngữ', 'Thư viện cũ')
--INSERT INTO KHOA VALUES (5, 'Công nghệ thông tin', 'A6')
GO